name: Build & deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Install dependencies
        run: dotnet restore src
      - name: Test project
        run: dotnet test src/Optivulcan.Test
      - name: Build Project
        run: dotnet pack -c Release src/Optivulcan
      - name: Publish to NuGet
        run: dotnet nuget push src/Optivulcan/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
